// <auto-generated />
namespace Food1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class changeCartTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeCartTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202412171010414_changeCartTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
